### ISSUE TITLE
Is that your actual API key?!?!

### ISSUE THREAD

**Issue by mikeboensel** [natolambert/blogcaster#2]
https://github.com/natolambert/interconnects-tools/blob/6c917e46912603a5493d631799336bbef61b3a88/scripts/tts.py#L85

Might be boilerplate example code, but searching for that hash didn't find any results. If it is, you should probably remove it before someone runs up a bill on your account (remember to clean it out of your Git history too!).

Enjoying the blog, BTW.

**Comment by natolambert** [comment]
I turned it off before pushing, was easier than deleting it from git history ;)
Thanks anyways and thanks!
